# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.0.2a1.dev16+g5ebd912.d20220329'
version_tuple = (0, 0, 2, 'dev16', 'g5ebd912.d20220329')
